name: Build checks

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt


      - name: Check
        run: cargo check

      - name: Format check
        run: cargo fmt --check

      - name: Test
        run: cargo test

      - name: Benchmark
        run: cargo bench

      - name: Build
        run: cargo build

      - name: Run
        run: cargo run

